"""
Unity 6 Live Engine Bridge Implementation for OmniMesh.
Generates and installs OmniMeshUnityPostprocessor.cs into Unity project,
attaches LODGroup with custom screen heights, converts collider meshes to MeshCollider(convex=true),
configures two-sided alpha-test Impostor materials, and routes URP/HDRP Lit shaders and PBR MaskMaps.
"""

from __future__ import annotations

import logging
import os
import shutil
from typing import Any, Tuple

from .base import EngineBridgeBase

logger = logging.getLogger(__name__)

try:
    import bpy
except ImportError:
    bpy = None


class UnityLiveBridge(EngineBridgeBase):
    @classmethod
    def get_engine_name(cls) -> str:
        return "Unity 6"

    @classmethod
    def ping_engine(cls, project_dir: str = "") -> Tuple[bool, str]:
        """Validates Unity project directory structure."""
        if not project_dir:
            return False, "Unity Project Path not configured"

        assets_dir = os.path.join(project_dir, "Assets")
        if not os.path.isdir(assets_dir):
            return False, f"Invalid Unity Project: '{project_dir}'"

        clean_name = os.path.basename(project_dir.rstrip("/\\"))
        return True, f"Unity 6 Project Active: {clean_name}"

    @classmethod
    def generate_postprocessor_csharp_code(cls) -> str:
        """Generates C# AssetPostprocessor with LODGroup, MeshCollider, and Impostor routing."""
        lines = [
            "// Auto-generated by OmniMesh LOD Tool for Unity 6",
            "#if UNITY_EDITOR",
            "using UnityEngine;",
            "using UnityEditor;",
            "using UnityEngine.Rendering;",
            "using System.IO;",
            "using System.Linq;",
            "",
            "public class OmniMeshUnityPostprocessor : AssetPostprocessor",
            "{",
            "    private void OnPreprocessModel()",
            "    {",
            '        if (!assetPath.Contains("OmniMesh") && !assetImporter.userData.Contains("OmniMesh"))',
            "            return;",
            "",
            "        ModelImporter modelImporter = (ModelImporter)assetImporter;",
            "        modelImporter.materialImportMode = ModelImporterMaterialImportMode.ImportViaMaterialDescription;",
            "        modelImporter.normalCalculationMode = ModelImporterNormalCalculationMode.Unweighted;",
            "    }",
            "",
            "    private void OnPostprocessModel(GameObject root)",
            "    {",
            '        if (!assetPath.Contains("OmniMesh") && !assetImporter.userData.Contains("OmniMesh"))',
            "            return;",
            "",
            "        // 1. Process and configure convex collision hulls",
            "        var colliderTransforms = root.GetComponentsInChildren<Transform>()",
            '            .Where(t => System.Text.RegularExpressions.Regex.IsMatch(t.name, @"(_Collider\\d*|UCX_)", System.Text.RegularExpressions.RegexOptions.IgnoreCase))',
            "            .ToList();",
            "",
            "        foreach (var cTrans in colliderTransforms)",
            "        {",
            "            MeshFilter mf = cTrans.GetComponent<MeshFilter>();",
            "            if (mf != null && mf.sharedMesh != null)",
            "            {",
            "                MeshCollider mc = cTrans.gameObject.GetComponent<MeshCollider>() ?? cTrans.gameObject.AddComponent<MeshCollider>();",
            "                mc.sharedMesh = mf.sharedMesh;",
            "                mc.convex = true;",
            "            }",
            "            Renderer r = cTrans.GetComponent<Renderer>();",
            "            if (r != null) r.enabled = false;",
            "        }",
            "",
            "        // 2. Process and configure LODGroup (including Impostor)",
            "        var lodTransforms = root.GetComponentsInChildren<Transform>()",
            '            .Where(t => System.Text.RegularExpressions.Regex.IsMatch(t.name, @"(_LOD\\d+$|_Impostor)", System.Text.RegularExpressions.RegexOptions.IgnoreCase))',
            "            .OrderBy(t => t.name)",
            "            .ToList();",
            "",
            "        if (lodTransforms.Count <= 1) return;",
            "",
            "        LODGroup lodGroup = root.GetComponent<LODGroup>() ?? root.AddComponent<LODGroup>();",
            "        LOD[] currentLODs = new LOD[lodTransforms.Count];",
            "",
            "        for (int i = 0; i < lodTransforms.Count; i++)",
            "        {",
            "            var renderers = lodTransforms[i].GetComponentsInChildren<Renderer>();",
            "            float screenTransitionHeight = Mathf.Pow(0.5f, i + 1);",
            "            currentLODs[i] = new LOD(screenTransitionHeight, renderers);",
            "        }",
            "",
            "        lodGroup.SetLODs(currentLODs);",
            "        lodGroup.RecalculateBounds();",
            "        EditorUtility.SetDirty(root);",
            "    }",
            "",
            "    private void OnPostprocessMaterial(Material material)",
            "    {",
            "        string dir = Path.GetDirectoryName(assetPath);",
            '        string texDir = Path.Combine(dir, "Textures");',
            "        if (!Directory.Exists(texDir)) return;",
            "",
            '        string matName = material.name.Replace(" (Instance)", "").Trim();',
            '        bool isImpostor = matName.IndexOf("Impostor", System.StringComparison.OrdinalIgnoreCase) >= 0;',
            "",
            "        RenderPipelineAsset currentPipeline = GraphicsSettings.currentRenderPipeline;",
            '        string pipelineType = currentPipeline != null ? currentPipeline.GetType().Name : "BuiltIn";',
            "",
            '        if (pipelineType.Contains("Universal") || pipelineType.Contains("URP"))',
            "        {",
            '            material.shader = Shader.Find("Universal Render Pipeline/Lit") ?? material.shader;',
            '            AssignTextureIfExists(material, "_BaseMap", texDir, $"T_{matName}_BaseColor.png");',
            '            AssignTextureIfExists(material, "_MetallicGlossMap", texDir, $"T_{matName}_MaskMap.png");',
            '            AssignTextureIfExists(material, "_BumpMap", texDir, $"T_{matName}_Normal.png");',
            "",
            "            if (isImpostor)",
            "            {",
            '                material.SetFloat("_AlphaClip", 1.0f);',
            '                material.SetFloat("_Cutoff", 0.33f);',
            '                material.SetFloat("_Cull", 0.0f); // Two-Sided',
            '                material.EnableKeyword("_ALPHATEST_ON");',
            "                material.renderQueue = (int)UnityEngine.Rendering.RenderQueue.AlphaTest;",
            "            }",
            "        }",
            '        else if (pipelineType.Contains("HighDefinition") || pipelineType.Contains("HDRP"))',
            "        {",
            '            material.shader = Shader.Find("HDRP/Lit") ?? material.shader;',
            '            AssignTextureIfExists(material, "_BaseColorMap", texDir, $"T_{matName}_BaseColor.png");',
            '            AssignTextureIfExists(material, "_MaskMap", texDir, $"T_{matName}_MaskMap.png");',
            '            AssignTextureIfExists(material, "_NormalMap", texDir, $"T_{matName}_Normal.png");',
            "",
            "            if (isImpostor)",
            "            {",
            '                material.SetFloat("_AlphaCutoffEnable", 1.0f);',
            '                material.SetFloat("_AlphaCutoff", 0.33f);',
            '                material.SetFloat("_DoubleSidedEnable", 1.0f);',
            "            }",
            "        }",
            "    }",
            "",
            "    private static void AssignTextureIfExists(Material mat, string propertyName, string dir, string filename)",
            "    {",
            "        string fullPath = Path.Combine(dir, filename);",
            "        if (!File.Exists(fullPath)) return;",
            "",
            "        string relativePath = \"Assets\" + fullPath.Substring(Application.dataPath.Length).Replace('\\\\', '/');",
            "        Texture2D tex = AssetDatabase.LoadAssetAtPath<Texture2D>(relativePath);",
            "        if (tex != null && mat.HasProperty(propertyName))",
            "        {",
            "            mat.SetTexture(propertyName, tex);",
            "        }",
            "    }",
            "}",
            "#endif",
        ]
        return "\n".join(lines) + "\n"

    @classmethod
    def generate_postprocessor_script(cls) -> str:
        return cls.generate_postprocessor_csharp_code()

    @classmethod
    def install_companion_scripts(cls, project_dir: str) -> Tuple[bool, str]:
        """Installs OmniMeshUnityPostprocessor.cs into Assets/Editor/."""
        if not project_dir or not os.path.exists(project_dir):
            return False, "Unity Project directory does not exist."

        editor_dir = os.path.join(project_dir, "Assets", "Editor")
        os.makedirs(editor_dir, exist_ok=True)

        script_path = os.path.join(editor_dir, "OmniMeshUnityPostprocessor.cs")
        try:
            with open(script_path, "w", encoding="utf-8") as f:
                f.write(cls.generate_postprocessor_csharp_code())
            return True, f"Installed Unity Postprocessor: {script_path}"
        except Exception as e:
            return False, f"Failed to install Unity postprocessor: {str(e)}"

    @classmethod
    def sync_asset(
        cls,
        context: Any,
        export_dir: str,
        asset_name: str,
        project_dir: str = "",
    ) -> Tuple[bool, str]:
        """Syncs exported package to Unity project."""
        target_dir = project_dir
        if not target_dir and context and hasattr(context, "scene"):
            props = getattr(context.scene, "lod_tool", None)
            if props and props.engine_project_path:
                target_dir = os.path.abspath(bpy.path.abspath(props.engine_project_path)) if bpy else ""

        if not target_dir:
            return False, "Unity Project Path not configured in OmniMesh"

        if not export_dir or not os.path.exists(export_dir):
            return False, f"Export directory not found: '{export_dir}'"

        import re

        clean_name = os.path.basename(str(asset_name))
        clean_asset = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", clean_name).strip() or "SM_Asset"

        fbx_path = os.path.join(export_dir, f"{clean_asset}.fbx")
        if not os.path.exists(fbx_path):
            fbx_files = [f for f in os.listdir(export_dir) if f.lower().endswith(".fbx")]
            if fbx_files:
                fbx_path = os.path.join(export_dir, fbx_files[0])
            else:
                return False, f"Exported FBX not found: '{fbx_path}'"

        is_valid, msg = cls.ping_engine(target_dir)
        if not is_valid:
            return False, msg

        # Ensure companion script is installed
        cls.install_companion_scripts(target_dir)

        resolved_proj = os.path.abspath(target_dir)
        dest_folder = os.path.abspath(os.path.join(resolved_proj, "Assets", "OmniMesh_Exports", clean_asset))
        if not dest_folder.startswith(resolved_proj):
            return False, "Directory traversal detected in asset name."

        try:
            os.makedirs(dest_folder, exist_ok=True)
            copied_count = 0
            if os.path.isdir(export_dir):
                for item in os.listdir(export_dir):
                    s = os.path.join(export_dir, item)
                    d = os.path.join(dest_folder, item)
                    if os.path.isdir(s):
                        if os.path.exists(d):
                            shutil.rmtree(d)
                        shutil.copytree(s, d)
                        copied_count += 1
                    elif os.path.isfile(s):
                        shutil.copy2(s, d)
                        copied_count += 1
        except (OSError, shutil.Error) as exc:
            return False, f"Failed copying asset files to Unity project: {exc}"

        return True, f"Synced {clean_asset} ({copied_count} items) to Unity: Assets/OmniMesh_Exports/{clean_asset}/"


# Class alias for backward compatibility
UnityBridge = UnityLiveBridge
